### ISSUE TITLE
make HTTP server port configurable

### ISSUE THREAD

**Issue by derhuerst** [yeicor-3d/yet-another-cad-viewer#207]
While I can configure the HTTP server's address & port using `$YACV_HOST`/`$YACV_PORT`, the client will always connect to `127.0.0.1:32323`. This causes problems when
- setting `$YACV_PORT` to something other than `32323`;
- the server will not be available on `127.0.0.1`, when I bind it to a different network interface (e.g. the Wireguard one only);
- the HTTP server is behind a port/address making (e.g. an HTTP reverse proxy or Docker), because then it's public host and/or port may be different from the one it's listening on;
- with IPv6

I propose:
- passing `$YACV_HOST`/`$YACV_PORT` through to the client, but also
- allowing to overwrite it manually (to cover the HTTP reverse proxy use case).

https://github.com/yeicor-3d/yet-another-cad-viewer/blob/ea181dac0b8369002f2475a2775c84b68b4fadac/yacv_server/yacv.py#L172

https://github.com/yeicor-3d/yet-another-cad-viewer/blob/ea181dac0b8369002f2475a2775c84b68b4fadac/frontend/misc/settings.ts#L13

I stumbled upon this when [wrapping YACV into a Docker image](https://github.com/derhuerst/build123d-docker/blob/8116ea1fbf962b36dcf006b0dc6b10f45f063bfb/Dockerfile#L42-L45). Unless using [host networking](https://docs.docker.com/engine/network/drivers/host/), the HTTP server must listen on `0.0.0.0` but the client should still connect to `localhost`.

**Comment by Yeicor** [comment]
You can actually change the frontend URL by adding the `preload=dev+http://<host>:<port>/` parameter to the URL query. For example, using [this link](https://yeicor-3d.github.io/yet-another-cad-viewer/?preload=dev+http://127.0.0.1:12345/) connects to port 12345 instead. You can even add multiple preload parameters to connect to different servers or to preload external .glb models.

However, when the client is served by the YACV backend rather than being deployed standalone, it should ideally auto-detect and connect to the same host and port as the backend. Using the same URL from which the frontend is loaded would handle most issues with reverse proxies, where the backend isn't aware of the exact address from which it will be accessed.

To implement this, it may be as simple as checking if `/api/updates` exists on the frontend's base URL, and if so, set that URL as the backend default.

Thanks for raising this issue! I'll keep it open as a reminder to improve auto-detection and configuration in this scenario.

**Comment by derhuerst** [comment]
I don't mind if this is solved via some "smart" `/api/updates` checking, or via a basic `preload` parameter being added by the server. As long as it allows me to use YACV from the command-line the scenarios described above, I'm happy. 🙂

**Comment by Yeicor** [comment]
This should just work on v0.9.2: open the frontend served from the backend and it will connect to it without manual intervention. However, you can still use the `preload` query parameter to specify custom backends, e.g., connecting to your backend from the static deployment of the frontend on github.io.

Please test it and reopen if you experience any issues.
